// ============================================================
// Brain Bot V15 — Room Definitions
// All 16 rooms of the World HQ with tile coordinates,
// visual properties, and API mappings.
// ============================================================

import type { RoomDefinition, NPCDefinition } from './types/world.types';

// Tile size in pixels
export const TILE_SIZE = 16;

// Map dimensions in tiles (1920×1152 pixels)
export const MAP_COLS = 120;
export const MAP_ROWS = 72;

// ── Room Layout Grid (tile coordinates) ──────────────────────────────────────
//
//  Row 1 (y=2, h=14):   CEO | Meeting | Mission | Training | Risk
//  Row 2 (y=20, h=14):  Intel | [path] | [PLAZA] | [path] | ML
//  Row 3 (y=38, h=14):  Futures | [path] | Replay | Teleport | Command
//  Row 4 (y=56, h=12):  Portfolio | Emergency | [path] | Data | Server
//
// ─────────────────────────────────────────────────────────────────────────────

export const ROOM_DEFINITIONS: RoomDefinition[] = [
  // ─── Row 1 ────────────────────────────────────────────────
  {
    id: 'ceo',
    name: 'CEO Room',
    tx: 2, ty: 2, tw: 18, th: 14,
    floorTile: 'floor_ceo',
    wallColor: 0x0a0a2e,
    floorColor: 0x12124a,
    accentColor: 0xffd700,
    labelColor: '#ffd700',
    npcId: 'ceo_agent',
    apiEndpoint: '/api/decision',
    modalType: 'ceo',
    description: 'CEO decision command room — live confidence & signal',
  },
  {
    id: 'meeting',
    name: 'Meeting Room',
    tx: 22, ty: 2, tw: 14, th: 14,
    floorTile: 'floor_meeting',
    wallColor: 0x1a1a2a,
    floorColor: 0x222235,
    accentColor: 0x8888ff,
    labelColor: '#aaaaff',
    npcId: null,
    apiEndpoint: '/api/agents',
    modalType: 'meeting_room',
    description: 'Agent council chamber — all agent reports',
  },
  {
    id: 'mission',
    name: 'Mission Board',
    tx: 38, ty: 2, tw: 20, th: 14,
    floorTile: 'floor_mission',
    wallColor: 0x200a2e,
    floorColor: 0x2e0a3f,
    accentColor: 0xaa44ff,
    labelColor: '#cc88ff',
    npcId: 'mission_controller',
    apiEndpoint: '/api/missions',
    modalType: 'mission_board',
    description: 'Live mission Kanban pipeline',
  },
  {
    id: 'training',
    name: 'Training Room',
    tx: 60, ty: 2, tw: 12, th: 14,
    floorTile: 'floor_training',
    wallColor: 0x0a1a1a,
    floorColor: 0x0a2020,
    accentColor: 0x00ffaa,
    labelColor: '#00ffaa',
    npcId: null,
    apiEndpoint: '/api/ml/performance',
    modalType: 'training_room',
    description: 'ML model training & performance metrics',
  },
  {
    id: 'risk',
    name: 'Risk Center',
    tx: 74, ty: 2, tw: 18, th: 14,
    floorTile: 'floor_risk',
    wallColor: 0x2e0a0a,
    floorColor: 0x3f0a0a,
    accentColor: 0xff4444,
    labelColor: '#ff8888',
    npcId: 'risk_agent',
    apiEndpoint: '/api/system/health',
    modalType: 'risk_center',
    description: 'Real-time risk dashboard & circuit breakers',
  },

  // ─── Row 2 ────────────────────────────────────────────────
  {
    id: 'intelligence',
    name: 'Intelligence Lab',
    tx: 2, ty: 20, tw: 18, th: 14,
    floorTile: 'floor_intelligence',
    wallColor: 0x0a1a0f,
    floorColor: 0x0a2510,
    accentColor: 0x00ff88,
    labelColor: '#00ff88',
    npcId: 'smc_agent',
    apiEndpoint: '/api/intelligence',
    modalType: 'intelligence_lab',
    description: 'SMC analysis & market intelligence feed',
  },
  {
    id: 'plaza',
    name: 'Central Plaza',
    tx: 42, ty: 22, tw: 16, th: 12,
    floorTile: 'floor_plaza',
    wallColor: 0x181820,
    floorColor: 0x22222a,
    accentColor: 0x44ddff,
    labelColor: '#44ddff',
    npcId: 'journal_agent',
    apiEndpoint: '/api/health',
    modalType: 'central_plaza',
    description: 'Brain Bot HQ Central — system overview',
  },
  {
    id: 'ml_lab',
    name: 'ML Laboratory',
    tx: 96, ty: 20, tw: 20, th: 14,
    floorTile: 'floor_ml',
    wallColor: 0x0a0a2e,
    floorColor: 0x0f0f40,
    accentColor: 0x4488ff,
    labelColor: '#88aaff',
    npcId: 'ml_agent',
    apiEndpoint: '/api/ml/status',
    modalType: 'ml_lab',
    description: 'ML ensemble — XGBoost, LightGBM, predictions',
  },

  // ─── Row 3 ────────────────────────────────────────────────
  {
    id: 'futures',
    name: 'Futures Lab',
    tx: 2, ty: 38, tw: 18, th: 14,
    floorTile: 'floor_futures',
    wallColor: 0x1a0f00,
    floorColor: 0x251500,
    accentColor: 0xff8800,
    labelColor: '#ffaa44',
    npcId: 'futures_agent',
    apiEndpoint: '/api/futures',
    modalType: 'futures_lab',
    description: 'OI, funding rate, long/short ratio analysis',
  },
  {
    id: 'replay',
    name: 'Replay Theater',
    tx: 26, ty: 38, tw: 22, th: 14,
    floorTile: 'floor_replay',
    wallColor: 0x1a001a,
    floorColor: 0x250025,
    accentColor: 0xff44ff,
    labelColor: '#ff88ff',
    npcId: null,
    apiEndpoint: '/api/journal',
    modalType: 'replay_theater',
    description: 'Trade replay & journal review theater',
  },
  {
    id: 'teleport',
    name: 'Teleport Hub',
    tx: 54, ty: 42, tw: 10, th: 10,
    floorTile: 'floor_teleport',
    wallColor: 0x002020,
    floorColor: 0x003030,
    accentColor: 0x00ffff,
    labelColor: '#00ffff',
    npcId: null,
    apiEndpoint: null,
    modalType: 'teleport_hub',
    description: 'Instant teleport to any room',
  },
  {
    id: 'command',
    name: 'Command Center',
    tx: 96, ty: 38, tw: 20, th: 14,
    floorTile: 'floor_command',
    wallColor: 0x001a1a,
    floorColor: 0x002020,
    accentColor: 0x00cccc,
    labelColor: '#00eeee',
    npcId: 'trader_agent',
    apiEndpoint: '/api/command/state',
    modalType: 'command_center',
    description: 'Execution control — Commander Interface',
  },

  // ─── Row 4 ────────────────────────────────────────────────
  {
    id: 'portfolio',
    name: 'Portfolio Vault',
    tx: 2, ty: 56, tw: 18, th: 12,
    floorTile: 'floor_portfolio',
    wallColor: 0x1a1500,
    floorColor: 0x251e00,
    accentColor: 0xddaa00,
    labelColor: '#ffcc44',
    npcId: 'portfolio_agent',
    apiEndpoint: '/api/paper',
    modalType: 'portfolio_vault',
    description: 'Live positions, PnL, and trade history',
  },
  {
    id: 'emergency',
    name: 'Emergency Room',
    tx: 26, ty: 56, tw: 16, th: 12,
    floorTile: 'floor_emergency',
    wallColor: 0x3f0000,
    floorColor: 0x500000,
    accentColor: 0xff0000,
    labelColor: '#ff6666',
    npcId: 'regime_agent',
    apiEndpoint: '/api/regime',
    modalType: 'emergency_room',
    description: 'Market regime & emergency protocols',
  },
  {
    id: 'data_center',
    name: 'Data Center',
    tx: 62, ty: 56, tw: 16, th: 12,
    floorTile: 'floor_data',
    wallColor: 0x0a0a10,
    floorColor: 0x0f0f18,
    accentColor: 0x6666ff,
    labelColor: '#8888ff',
    npcId: null,
    apiEndpoint: '/api/events',
    modalType: 'data_center',
    description: 'Event bus, data pipeline & raw feeds',
  },
  {
    id: 'server',
    name: 'Server Room',
    tx: 84, ty: 56, tw: 20, th: 12,
    floorTile: 'floor_server',
    wallColor: 0x0a0a0a,
    floorColor: 0x101010,
    accentColor: 0x22ff44,
    labelColor: '#44ff66',
    npcId: null,
    apiEndpoint: '/api/system/health',
    modalType: 'server_room',
    description: 'System health, watchdog & reconciliation',
  },
];

// ── NPC Definitions ──────────────────────────────────────────────────────────

export const NPC_DEFINITIONS: NPCDefinition[] = [
  {
    id: 'ceo_agent',
    name: 'CEO',
    role: 'Chief Executive',
    roomId: 'ceo',
    bodyColor: 0x1a3a8a,
    headColor: 0xf4c87a,
    startTx: 8, startTy: 7,
    icon: '👔',
  },
  {
    id: 'risk_agent',
    name: 'Risk Manager',
    role: 'Risk Control',
    roomId: 'risk',
    bodyColor: 0x8a1a1a,
    headColor: 0xf4a07a,
    startTx: 82, startTy: 7,
    icon: '⚠️',
  },
  {
    id: 'smc_agent',
    name: 'SMC Analyst',
    role: 'Smart Money Concepts',
    roomId: 'intelligence',
    bodyColor: 0x1a6a1a,
    headColor: 0xd4e07a,
    startTx: 8, startTy: 25,
    icon: '📊',
  },
  {
    id: 'ml_agent',
    name: 'ML Engineer',
    role: 'Machine Learning',
    roomId: 'ml_lab',
    bodyColor: 0x1a1a8a,
    headColor: 0xa4d8f0,
    startTx: 104, startTy: 25,
    icon: '🤖',
  },
  {
    id: 'futures_agent',
    name: 'Futures Analyst',
    role: 'OI & Funding',
    roomId: 'futures',
    bodyColor: 0x8a4a00,
    headColor: 0xf4c09a,
    startTx: 8, startTy: 43,
    icon: '📈',
  },
  {
    id: 'trader_agent',
    name: 'Trader',
    role: 'Trade Execution',
    roomId: 'command',
    bodyColor: 0x006a6a,
    headColor: 0xc0e0e0,
    startTx: 104, startTy: 43,
    icon: '💹',
  },
  {
    id: 'portfolio_agent',
    name: 'Portfolio Manager',
    role: 'Portfolio Control',
    roomId: 'portfolio',
    bodyColor: 0x6a5a00,
    headColor: 0xf0e080,
    startTx: 8, startTy: 60,
    icon: '💼',
  },
  {
    id: 'regime_agent',
    name: 'Regime Analyst',
    role: 'Market Regime',
    roomId: 'emergency',
    bodyColor: 0x8a0000,
    headColor: 0xff9090,
    startTx: 32, startTy: 60,
    icon: '🔴',
  },
  {
    id: 'mission_controller',
    name: 'Mission Control',
    role: 'Mission Pipeline',
    roomId: 'mission',
    bodyColor: 0x4a006a,
    headColor: 0xe0a0ff,
    startTx: 46, startTy: 7,
    icon: '🎯',
  },
  {
    id: 'journal_agent',
    name: 'Journal Agent',
    role: 'Trade Journal',
    roomId: 'plaza',
    bodyColor: 0x2a3050,
    headColor: 0xa0c0ff,
    startTx: 48, startTy: 27,
    icon: '📝',
  },
];
