"""
tools/github_actions.py — Bundle Manager: remote-facing actions

Naming note (an interpretation call, documented rather than left
implicit): this is named for the *actions themselves* — the operations
that actually reach the `origin` remote (fetch a branch in, push a
branch out) — not GitHub Actions the CI product. No `.github/workflows/`
YAML is generated by this module or anywhere in this package; wiring
this tool into CI is a reasonable follow-up but wasn't asked for
explicitly, and a real CI workflow needs its own secrets/permissions
design this tool shouldn't silently assume. tools/git_utils.py owns
generic local git plumbing; this module owns the higher-level, always-
remote-touching workflow built on top of it.

import_bundle() is the single entry point that ties together
bundle_utils (discovery/parsing), git_utils (verify/fetch/checkout/push),
and history (duplicate prevention) into the full per-bundle flow the
brief describes. bundle_manager.py's CLI calls this once per discovered
bundle; nothing else should need to re-implement this sequence.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from tools import bundle_utils, git_utils
from tools.history import BundleHistory
from utils.logger import get_logger

logger = get_logger(__name__)


@dataclass(frozen=True)
class ImportResult:
    bundle_path:  Path
    branch:       str | None
    sha:          str | None
    status:       str            # "applied" | "failed" | "skipped_duplicate" | "dry_run"
    reason:       str | None
    final_path:   Path | None = None   # where the bundle file ended up


def import_bundle(
    bundle_path: Path,
    repo_dir: Path,
    history: BundleHistory,
    applied_dir: Path,
    failed_dir: Path,
    base_branch: str = "main",
    remote: str = "origin",
    push: bool = True,
    dry_run: bool = False,
    force: bool = False,
    push_retries: int = 3,
    git_timeout: int = 120,
) -> ImportResult:
    """
    Full per-bundle workflow:
      1. verify
      2. extract branch + SHA (exactly one refs/heads/* ref required)
      3. reject if SHA already in history (status == "applied")
      4. checkout base_branch first (fetching into the currently-checked-
         -out branch is refused by git — see git_utils.py's docstring
         note; this is not optional, confirmed by direct testing)
      5. fetch the branch out of the bundle file
      6. checkout the feature branch
      7. push (unless push=False, e.g. for local-only testing)
      8. move the bundle file to applied_dir or failed_dir
      9. record the outcome in history (NOT saved to disk here — caller
         calls history.save() once after processing the whole incoming/
         batch, so one crash mid-batch doesn't require re-verifying
         bundles already fully processed this run)

    dry_run=True stops after step 3 and reports what WOULD happen —
    verify + extract + duplicate-check only, no fetch/checkout/push, no
    file move, no history mutation. Always run this first against an
    unfamiliar bundle.
    """
    name = bundle_path.name

    ok, verify_message = git_utils.verify_bundle(bundle_path, repo_dir, timeout=git_timeout)
    if not ok:
        return _fail(bundle_path, None, None, f"git bundle verify failed: {verify_message}",
                      history, failed_dir, dry_run)

    try:
        info = bundle_utils.extract_branch_and_sha(bundle_path, repo_dir)
    except bundle_utils.BundleFormatError as exc:
        return _fail(bundle_path, None, None, str(exc), history, failed_dir, dry_run)

    if history.has_sha(info.sha):
        logger.info("github_actions: %s (sha=%s) already imported — skipping", name, info.sha[:12])
        if dry_run:
            return ImportResult(bundle_path, info.branch, info.sha, "dry_run",
                                 "already imported (duplicate SHA)")
        final_path = bundle_utils.move_bundle(bundle_path, applied_dir)
        return ImportResult(bundle_path, info.branch, info.sha, "skipped_duplicate",
                             "already imported (duplicate SHA)", final_path)

    if dry_run:
        logger.info(
            "github_actions: [dry-run] %s -> branch=%s sha=%s would be imported%s",
            name, info.branch, info.sha[:12], " and pushed" if push else "",
        )
        return ImportResult(bundle_path, info.branch, info.sha, "dry_run", None)

    try:
        # Step 4 — see docstring: must not already be on the target branch.
        current = git_utils.get_current_branch(repo_dir)
        if current != base_branch:
            if not git_utils.branch_exists(base_branch, repo_dir):
                raise git_utils.GitCommandError(
                    ["checkout", base_branch], 1, "",
                    f"base branch '{base_branch}' does not exist locally",
                )
            git_utils.checkout_branch(base_branch, repo_dir, timeout=git_timeout)

        git_utils.fetch_branch_from_bundle(
            bundle_path, info.branch, repo_dir, force=force, timeout=git_timeout,
        )
        git_utils.checkout_branch(info.branch, repo_dir, timeout=git_timeout)

        pushed = False
        if push:
            git_utils.push_branch(
                info.branch, repo_dir, remote=remote, force=force,
                retries=push_retries, timeout=git_timeout,
            )
            pushed = True

    except git_utils.GitCommandError as exc:
        reason = f"{exc.cmd[1] if len(exc.cmd) > 1 else 'git'} failed: {exc.stderr.strip()[:500]}"
        return _fail(bundle_path, info.branch, info.sha, reason, history, failed_dir, dry_run)

    final_path = bundle_utils.move_bundle(bundle_path, applied_dir)
    history.record_applied(info.sha, info.branch, name, pushed=pushed)
    logger.info(
        "github_actions: %s imported OK -> branch=%s sha=%s pushed=%s",
        name, info.branch, info.sha[:12], pushed,
    )
    return ImportResult(bundle_path, info.branch, info.sha, "applied", None, final_path)


def _fail(
    bundle_path: Path, branch: str | None, sha: str | None, reason: str,
    history: BundleHistory, failed_dir: Path, dry_run: bool,
) -> ImportResult:
    logger.error("github_actions: %s failed: %s", bundle_path.name, reason)
    if dry_run:
        return ImportResult(bundle_path, branch, sha, "dry_run", reason)
    final_path = bundle_utils.move_bundle(bundle_path, failed_dir)
    if sha:
        history.record_failed(sha, branch or "", bundle_path.name, reason)
    return ImportResult(bundle_path, branch, sha, "failed", reason, final_path)
